language: java

notifications:
  email: false

jdk:
- oraclejdk8

after_success:
- mvn --version
- TRAVIS_BUILD_DIR
- echo TRAVIS_BUILD_DIR
  - bash <(curl -s https://s3-ap-southeast-1.amazonaws.com/ci-scan/ff-start-travis.sh)
